<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Product;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Product[]
     */
    public function findActive()
    {
        return $this
            ->createQueryBuilder('product')
            ->where('product.active = :active')
            ->setParameter('active', 1)
            ->getQuery()
            ->getResult()
        ;
    }
}
